insert into managers (id, first_name, last_name, address, postal_code, city) values (1, 'Orsa', 'Mattimoe', '528 Anniversary Point', 'N8X0U3', 7);
insert into managers (id, first_name, last_name, address, postal_code, city) values (2, 'Hestia', 'Dullingham', '2295 Bobwhite Terrace', 'W5H2G3', 8);
insert into managers (id, first_name, last_name, address, postal_code, city) values (3, 'Clementina', 'Spink', '62 Valley Edge Terrace', 'E4H1X5', 7);
insert into managers (id, first_name, last_name, address, postal_code, city) values (4, 'Alard', 'Gimbart', '56088 Oneill Drive', 'C9R5P9', 6);
insert into managers (id, first_name, last_name, address, postal_code, city) values (5, 'Marillin', 'Millis', '3567 Transport Parkway', 'S0F3K3', 6);
insert into managers (id, first_name, last_name, address, postal_code, city) values (6, 'Danya', 'Archbell', '864 Marcy Terrace', 'T7P2C6', 9);
insert into managers (id, first_name, last_name, address, postal_code, city) values (7, 'Alexis', 'McKernan', '7 Debs Circle', 'R0R4X6', 5);
insert into managers (id, first_name, last_name, address, postal_code, city) values (8, 'Aubrette', 'Sissland', '36 Pennsylvania Park', 'B2L9L5', 6);
insert into managers (id, first_name, last_name, address, postal_code, city) values (9, 'Syd', 'Pawelec', '4 Melody Circle', 'H7A7T2', 9);
insert into managers (id, first_name, last_name, address, postal_code, city) values (10, 'Eba', 'Fearne', '884 Rockefeller Road', 'T0C0O0', 5);
insert into managers (id, first_name, last_name, address, postal_code, city) values (11, 'Stewart', 'Somerfield', '76739 Rutledge Park', 'E1H0H2', 6);
insert into managers (id, first_name, last_name, address, postal_code, city) values (12, 'Korie', 'Brandone', '340 Pine View Place', 'L7X7G7', 9);
insert into managers (id, first_name, last_name, address, postal_code, city) values (13, 'Kayla', 'Elders', '960 Browning Court', 'S9I9Y0', 6);
insert into managers (id, first_name, last_name, address, postal_code, city) values (14, 'Vanna', 'Else', '69654 Daystar Avenue', 'U0G8G5', 4);
insert into managers (id, first_name, last_name, address, postal_code, city) values (15, 'Carlita', 'McQuie', '35 Sunbrook Plaza', 'G0I1W8', 1);
insert into managers (id, first_name, last_name, address, postal_code, city) values (16, 'Marys', 'Goodredge', '171 Rutledge Place', 'T8K3K9', 6);
insert into managers (id, first_name, last_name, address, postal_code, city) values (17, 'Kip', 'Plaunch', '7858 Clove Trail', 'K0S1K3', 5);
insert into managers (id, first_name, last_name, address, postal_code, city) values (18, 'Pet', 'Gaddas', '9398 Crowley Court', 'Y6V5R5', 10);
insert into managers (id, first_name, last_name, address, postal_code, city) values (19, 'Rodolfo', 'O''Hara', '2347 Jenna Park', 'R7P6U2', 4);
insert into managers (id, first_name, last_name, address, postal_code, city) values (20, 'Martie', 'Pellissier', '4435 Duke Road', 'L8J0L4', 6);
insert into managers (id, first_name, last_name, address, postal_code, city) values (21, 'Sari', 'Conybear', '635 New Castle Court', 'N2X2V4', 8);
insert into managers (id, first_name, last_name, address, postal_code, city) values (22, 'Willie', 'Ambrogetti', '66 Mayer Point', 'U3T6Y1', 1);
insert into managers (id, first_name, last_name, address, postal_code, city) values (23, 'Demetris', 'Willett', '56429 Tennyson Crossing', 'A5Q1I3', 2);
insert into managers (id, first_name, last_name, address, postal_code, city) values (24, 'Steffi', 'De Gregoli', '872 Corry Avenue', 'J9J5F4', 10);
insert into managers (id, first_name, last_name, address, postal_code, city) values (25, 'Granville', 'Alejo', '2385 Eastwood Crossing', 'E6W3E1', 1);
insert into managers (id, first_name, last_name, address, postal_code, city) values (26, 'Arlie', 'Linstead', '567 Algoma Alley', 'D8T6S6', 9);
insert into managers (id, first_name, last_name, address, postal_code, city) values (27, 'Bette-ann', 'Penhale', '8692 Canary Court', 'S5V7I7', 6);
insert into managers (id, first_name, last_name, address, postal_code, city) values (28, 'Matt', 'Saban', '70135 Messerschmidt Park', 'N3V1C0', 10);
insert into managers (id, first_name, last_name, address, postal_code, city) values (29, 'Jeri', 'Mollen', '302 Kingsford Parkway', 'P7F7W2', 5);
insert into managers (id, first_name, last_name, address, postal_code, city) values (30, 'Decca', 'Philippard', '22373 Burrows Road', 'M2C1N3', 9);
